export const SET_MUTUELLES = 'SET_MUTUELLES'
export const SET_CREDITS = 'SET_CREDITS'
export const SET_CREDIT = 'SET_CREDIT'
export const SET_MISE_FONDS = 'SET_MISE_FONDS'
export const SET_MISES_FONDS = 'SET_MISES_FONDS'

