
export const SET_CREDENTIALS = 'SET_CREDENTIALS'
export const INITIALIZE = 'INITIALIZE'
export const LOG_OUT = 'LOG_OUT'
export const SET_USER = 'SET_USER'
export const SET_USER_ID = 'SET_USER_ID'
export const SET_PHONE= 'SET_PHONE'
export const SET_USER_ROLES = 'SET_USER_ROLES'
export const SET_RESET_ROLES = 'SET_RESET_ROLES'
export const SET_NEW_ROLE ='SET_NEW_ROLE'
export const ADD_USER_ROLES = 'ADD_USER_ROLES'
export const REMOVE_ROLE ='REMOVE_ROLE'
