export const RESET = 'RESET'
export const UPDATE = 'UPDATE'
export const FETCH_USER_ASSOCIATION = 'FETCH_USER_ASSOCIATION'
export const FETCH_USER_ASSOCIATION_ROLES = 'FETCH_USER_ASSOCIATION_ROLES'
export const SET_CURRENT_ASSOCIATION = 'SET_CURRENT_ASSOCIATION'
export const SET_MEMBER_HAS = 'SET_MEMBER_HAS'
export const NO_COMMIT = 'NO_COMMIT'

import '../modules/membership.modules/store/mutation-types'
import '../modules/activities.modules/store/mutation-types'
import '../modules/news.modules/store/mutation-types'
import '../modules/calendar.modules/store/mutation-types'
import '../modules/documents.modules/store/mutation-types'
import '../modules/sessions.modules/store/mutation-types'
import '../modules/parameters.modules/store/mutation-types'
import '../modules/cycles.modules/store/mutation-types'
