export const SET_SOLIDARITES = 'SET_SOLIDARITES'
export const SET_ASSISTANCES = 'SET_ASSISTANCES'
export const SET_TYPE_ASSISTANCES = 'SET_TYPE_ASSISTANCES'
export const SET_TYPES_ASSISTANCES = 'SET_TYPES_ASSISTANCES'
